{ pkgs, inputs, ... }:

{
  environment.systemPackages = [
    inputs.noctalia.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];

  home-manager.users.user = {
    imports = [ inputs.noctalia.homeModules.default ];

    # Noctalia v5 user templates for apps not shipped by Noctalia yet.
    xdg.configFile."noctalia/templates/equibop.css".text = ''
      /**
       * @name Noctalia
       * @description Generated by Noctalia on every color-scheme change. Do not edit.
       */

      :root,
      body,
      .visual-refresh,
      .theme-light,
      .theme-dark,
      .theme-darker,
      .theme-midnight {
        color-scheme: dark !important;

        --font-primary: "SF Pro Display", "SF Pro", "SF Pro Text", "Helvetica Neue", Arial, sans-serif !important;
        --font-display: "SF Pro Display", "SF Pro", "SF Pro Text", "Helvetica Neue", Arial, sans-serif !important;
        --font-headline: "SF Pro Display", "SF Pro", "SF Pro Text", "Helvetica Neue", Arial, sans-serif !important;

        /* Keep Noctalia's generated colors, but expose them as translucent glass. */
        --noctalia-glass: color-mix(in srgb, {{colors.surface.default.hex}} 58%, transparent);
        --noctalia-glass-low: color-mix(in srgb, {{colors.surface_container_low.default.hex}} 46%, transparent);
        --noctalia-glass-high: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 70%, transparent);
        --noctalia-glass-highest: color-mix(in srgb, {{colors.surface_container_highest.default.hex}} 80%, transparent);
        --noctalia-glass-border: color-mix(in srgb, {{colors.outline_variant.default.hex}} 55%, transparent);
        --noctalia-glass-blur: blur(28px) saturate(1.25);
        --noctalia-chat-input: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 32%, transparent);

        --background-primary: var(--noctalia-glass) !important;
        --background-secondary: var(--noctalia-glass-low) !important;
        --background-secondary-alt: var(--noctalia-glass-low) !important;
        --background-tertiary: var(--noctalia-glass-high) !important;
        --background-accent: {{colors.primary.default.hex}} !important;
        --background-floating: var(--noctalia-glass-high) !important;
        --background-modifier-hover: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 62%, transparent) !important;
        --background-modifier-active: var(--noctalia-glass-highest) !important;
        --background-modifier-selected: var(--noctalia-glass-highest) !important;
        --background-modifier-accent: var(--noctalia-glass-border) !important;

        --channeltextarea-background: var(--noctalia-chat-input) !important;
        --modal-background: var(--noctalia-glass) !important;
        --modal-footer-background: var(--noctalia-glass-low) !important;

        --text-normal: {{colors.on_surface.default.hex}} !important;
        --text-muted: {{colors.on_surface_variant.default.hex}} !important;
        --text-link: {{colors.primary.default.hex}} !important;
        --header-primary: {{colors.on_surface.default.hex}} !important;
        --header-secondary: {{colors.on_surface_variant.default.hex}} !important;

        --interactive-normal: {{colors.on_surface.default.hex}} !important;
        --interactive-hover: {{colors.primary.default.hex}} !important;
        --interactive-active: {{colors.primary.default.hex}} !important;
        --interactive-muted: {{colors.outline.default.hex}} !important;

        --brand-experiment: {{colors.primary.default.hex}} !important;
        --brand-experiment-hover: {{colors.primary.default.hex}} !important;
        --mention-foreground: {{colors.primary.default.hex}} !important;
        --mention-background: color-mix(in srgb, {{colors.primary.default.hex}} 18%, transparent) !important;

        --bg-base-primary: var(--noctalia-glass) !important;
        --bg-base-secondary: var(--noctalia-glass-low) !important;
        --bg-base-tertiary: var(--noctalia-glass-low) !important;
        --bg-surface-raised: var(--noctalia-glass-high) !important;
        --bg-mod-faint: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 38%, transparent) !important;
        --bg-mod-subtle: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 55%, transparent) !important;
        --bg-mod-strong: var(--noctalia-glass-highest) !important;
        --background-base-lower: transparent !important;
        --background-surface-high: var(--noctalia-glass-high) !important;
        --background-mod-subtle: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 55%, transparent) !important;
        --background-mod-strong: var(--noctalia-glass-highest) !important;

        --custom-theme-base-color: {{colors.surface.default.hex}} !important;
        --custom-theme-base-color-dark: {{colors.surface.default.hex}} !important;
        --custom-theme-base-color-light: {{colors.surface.default.hex}} !important;
        --custom-theme-primary-color: {{colors.primary.default.hex}} !important;
        --custom-theme-secondary-color: {{colors.secondary.default.hex}} !important;
        --custom-theme-text-color: {{colors.on_surface.default.hex}} !important;
        --custom-theme-text-color-dark: {{colors.on_surface.default.hex}} !important;
        --custom-theme-text-color-light: {{colors.on_surface.default.hex}} !important;
      }

      body,
      #app-mount,
      .visual-refresh {
        font-family: "SF Pro Display", "SF Pro", "SF Pro Text", "Helvetica Neue", Arial, sans-serif !important;
      }

      html,
      body,
      #app-mount,
      #app-mount > div,
      .visual-refresh,
      [class*="appMount_"],
      [class*="app_"],
      [class*="bg_"],
      [class*="layers_"],
      [class*="layer_"],
      [class*="base_"],
      [class*="chat_"],
      [class*="chatContent_"],
      [class*="container_"],
      [class*="content_"],
      [class*="sidebar_"],
      [class*="privateChannels_"],
      [class*="guilds_"],
      [class*="scroller_"],
      [class*="members_"],
      [class*="member_"],
      [class*="panels_"],
      [class*="title_"],
      [class*="themed_"] {
        background-color: transparent !important;
        background: transparent !important;
      }

      [class*="chat_"],
      [class*="sidebar_"],
      [class*="membersWrap_"],
      [class*="panels_"],
      [class*="title_"],
      [class*="channelTextArea_"],
      [class*="scrollableContainer_"],
      [class*="floating_"],
      [class*="modal_"],
      [class*="popout_"] {
        backdrop-filter: var(--noctalia-glass-blur) !important;
      }

      /* Discord's message composer ignores the broad transparent-background
         reset in a few Visual Refresh builds and keeps an opaque
         --channeltextarea-background surface. Pin the composer to the same
         translucent glass used by Vesktop on desktop, without flattening the
         actual editable text area or buttons. */
      [class*="channelTextArea_"] {
        background: transparent !important;
      }

      [class*="channelTextArea_"] [class*="scrollableContainer_"],
      [class*="channelTextArea_"] [class*="themedBackground_"] {
        background: var(--noctalia-chat-input) !important;
        background-color: var(--noctalia-chat-input) !important;
        border: 1px solid var(--noctalia-glass-border) !important;
        box-shadow: none !important;
      }

      [class*="channelTextArea_"] [class*="inner_"],
      [class*="channelTextArea_"] [class*="textArea_"],
      [class*="channelTextArea_"] [class*="slateTextArea_"],
      [class*="channelTextArea_"] [data-slate-editor="true"] {
        background: transparent !important;
        background-color: transparent !important;
      }

      /* Vencord/QuickCSS editor (CodeMirror) */
      .cm-editor,
      .cm-editor .cm-scroller,
      .cm-editor .cm-content {
        background: {{colors.surface.default.hex}} !important;
        color: {{colors.on_surface.default.hex}} !important;
      }

      .cm-editor .cm-gutters {
        background: {{colors.surface_container.default.hex}} !important;
        border-color: {{colors.outline_variant.default.hex}} !important;
        color: {{colors.on_surface_variant.default.hex}} !important;
      }

      .cm-editor .cm-activeLine,
      .cm-editor .cm-activeLineGutter {
        background: {{colors.surface_container_high.default.hex}} !important;
      }

      .cm-editor .cm-cursor {
        border-left-color: {{colors.primary.default.hex}} !important;
      }

      .cm-editor .cm-selectionBackground,
      .cm-editor ::selection {
        background: color-mix(in srgb, {{colors.primary.default.hex}} 35%, transparent) !important;
      }

      /* Mention / ping count badges. Only color the pill itself; the unread
         top/bottom indicator containers span the server rail and become visible
         slabs when painted. */
      [class*="numberBadge_"],
      [class*="mentionsBadge_"] {
        background-color: {{colors.error.default.hex}} !important;
        color: {{colors.on_error.default.hex}} !important;
        backdrop-filter: none !important;
      }

      [class*="unreadMentionsIndicatorTop_"],
      [class*="unreadMentionsIndicatorBottom_"] {
        background: transparent !important;
        background-color: transparent !important;
      }

    '';

    xdg.configFile."noctalia/templates/warp.yaml".text = ''
      name: Noctalia
      accent: '{{colors.primary.default.hex}}'
      background: '{{colors.surface.default.hex}}'
      foreground: '{{colors.on_surface.default.hex}}'
      details: darker
      terminal_colors:
        normal:
          black: '{{colors.surface_variant.default.hex}}'
          red: '{{colors.error.default.hex}}'
          green: '{{colors.primary.default.hex}}'
          yellow: '{{colors.secondary.default.hex}}'
          blue: '{{colors.tertiary.default.hex}}'
          magenta: '{{colors.primary_container.default.hex}}'
          cyan: '{{colors.secondary_container.default.hex}}'
          white: '{{colors.on_surface.default.hex}}'
        bright:
          black: '{{colors.on_surface_variant.default.hex}}'
          red: '{{colors.error.default.hex}}'
          green: '{{colors.primary.default.hex}}'
          yellow: '{{colors.secondary.default.hex}}'
          blue: '{{colors.tertiary.default.hex}}'
          magenta: '{{colors.primary_container.default.hex}}'
          cyan: '{{colors.secondary_container.default.hex}}'
          white: '{{colors.on_surface.default.hex}}'
    '';

    xdg.configFile."noctalia/templates/tuxedo.toml".text = ''
      name = Noctalia
      bg = {{colors.surface.default.hex}}
      panel = {{colors.surface_container.default.hex}}
      border = {{colors.outline_variant.default.hex}}
      fg = {{colors.on_surface.default.hex}}
      dim = {{colors.on_surface_variant.default.hex}}
      accent = {{colors.primary.default.hex}}
      cursor = {{colors.surface_container_high.default.hex}}
      selection = {{colors.surface_container_highest.default.hex}}
      statusbar = {{colors.surface_container.default.hex}}
      status_fg = {{colors.on_surface.default.hex}}
      mode_fg = {{colors.on_primary.default.hex}}
      mode_bg = {{colors.primary.default.hex}}
      pri_a = {{colors.error.default.hex}}
      pri_b = {{colors.secondary.default.hex}}
      pri_c = {{colors.primary.default.hex}}
      pri_d = {{colors.tertiary.default.hex}}
      pri_other = {{colors.primary_container.default.hex}}
      project = {{colors.primary.default.hex}}
      context = {{colors.secondary.default.hex}}
      due = {{colors.secondary.default.hex}}
      overdue = {{colors.error.default.hex}}
      today = {{colors.error.default.hex}}
      done = {{colors.outline.default.hex}}
      selected = {{colors.surface_container_high.default.hex}}
      matched = {{colors.tertiary.default.hex}}
    '';

    # Kopuz music player. A kopuz theme is a map of 13 semantic color keys
    # (config.custom_themes."<id>".vars) that the app rewrites into its own
    # --color-* CSS variables at runtime. We render just those vars here as a
    # standalone JSON object; the post_hook merges it into kopuz's config.json
    # under a "custom-noctalia" theme and selects it, leaving the rest of the
    # config (library, server creds, last.fm keys) untouched.
    xdg.configFile."noctalia/templates/kopuz.json".text = ''
      {
        "bg": "{{colors.surface.default.hex}}",
        "raised": "{{colors.surface_container.default.hex}}",
        "surface": "{{colors.outline.default.hex}}",
        "text": "{{colors.on_surface.default.hex}}",
        "text-muted": "{{colors.on_surface_variant.default.hex}}",
        "progress": "{{colors.primary.default.hex}}",
        "accent-soft": "{{colors.tertiary.default.hex}}",
        "accent": "{{colors.primary.default.hex}}",
        "accent-alt": "{{colors.secondary.default.hex}}",
        "accent-deep": "{{colors.primary_container.default.hex}}",
        "highlight": "{{colors.secondary.default.hex}}",
        "highlight-dark": "{{colors.tertiary.default.hex}}",
        "danger": "{{colors.error.default.hex}}"
      }
    '';

    home.file.".local/bin/noctalia-apply-equibop-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        settings="$HOME/.config/equibop/settings/settings.json"
        mkdir -p "$HOME/.config/equibop/settings" "$HOME/.config/equibop/themes"

        if [ ! -s "$settings" ]; then
          printf '%s\n' '{"enabledThemes":["noctalia.css"]}' > "$settings"
          exit 0
        fi

        tmp=$(mktemp)
        jq '.enabledThemes = (((.enabledThemes // []) | map(select(. != "noctalia.theme.css" and . != "noctalia-material.theme.css"))) + ["noctalia.css"] | unique)' \
          "$settings" > "$tmp"
        mv "$tmp" "$settings"
      '';
    };

    home.file.".local/bin/noctalia-apply-warp-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        set_theme() {
          local cfgdir=$1 settings backup
          settings="$cfgdir/settings.toml"
          [[ -f "$settings" ]] || return 0
          backup="$settings.bak-before-noctalia-sync"
          [[ -f "$backup" ]] || cp -p "$settings" "$backup"
          awk '
            BEGIN { in_themes=0; wrote=0 }
            /^\[appearance\.themes\]/ { print; in_themes=1; next }
            /^\[/ && in_themes { if (!wrote) { print "system_theme = false"; print "theme = { custom = { name = \"Noctalia\", path = \"noctalia.yaml\" } }"; wrote=1 } in_themes=0 }
            in_themes && /^system_theme[[:space:]]*=/ { next }
            in_themes && /^theme[[:space:]]*=/ { next }
            { print }
            END { if (in_themes && !wrote) { print "system_theme = false"; print "theme = { custom = { name = \"Noctalia\", path = \"noctalia.yaml\" } }" } }
          ' "$settings" > "$settings.tmp"
          mv "$settings.tmp" "$settings"
        }

        set_theme "$HOME/.config/warp-oss"
      '';
    };

    home.file.".local/bin/noctalia-apply-tuxedo-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        cfg="$HOME/.config/tuxedo/config.toml"
        mkdir -p "$(dirname "$cfg")" "$HOME/.config/tuxedo/themes"
        touch "$cfg"
        if grep -q '^theme[[:space:]]*=' "$cfg"; then
          sed -i 's/^theme[[:space:]]*=.*/theme = Noctalia/' "$cfg"
        else
          tmp=$(mktemp)
          printf 'theme = Noctalia\n' > "$tmp"
          cat "$cfg" >> "$tmp"
          mv "$tmp" "$cfg"
        fi
      '';
    };

    home.file.".local/bin/noctalia-apply-kopuz-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        cfg="$HOME/.config/kopuz/config.json"
        vars="$HOME/.config/kopuz/noctalia-theme.json"
        # config.json is created on first run; the rendered vars come from the
        # Noctalia template. Do nothing until both exist.
        [ -s "$cfg" ] || exit 0
        [ -s "$vars" ] || exit 0

        tmp=$(mktemp)
        jq --slurpfile v "$vars" \
          '.custom_themes."custom-noctalia" = { name: "Noctalia", vars: $v[0] }
           | .theme = "custom-noctalia"' \
          "$cfg" > "$tmp"
        mv "$tmp" "$cfg"
      '';
    };

    programs.noctalia = {
      enable = true;
      settings = {
        shell.time_format = "{:%-I:%M %p}";
        # Noctalia v5 reads shell.font_family for its own UI. Keep this
        # declarative so runtime/state resets after suspend or restart cannot
        # fall back to the default sans font.
        shell.font_family = "SF Pro Display";
        widget.workspaces.hide_when_empty = true;

        shell.shadow.alpha = 0.31;
        shell.panel.transparency_mode = "glass";

        dock.enabled = false;
        dock.background_opacity = 0.31;
        dock.active_opacity = 0.31;
        dock.inactive_opacity = 0.31;

        notification.background_opacity = 0.31;
        notification.scale = 0.85;

        bar.Main.background_opacity = 0.31;

        # Built-in v5 templates plus user templates for apps not shipped by
        # Noctalia yet (Warp).
        theme.templates = {
          builtin_ids = [ "helix" "starship" ];
          user = {
            equibop = {
              input_path = "templates/equibop.css";
              output_path = "~/.config/equibop/themes/noctalia.css";
              post_hook = "~/.local/bin/noctalia-apply-equibop-theme";
            };
            warp_oss = {
              input_path = "templates/warp.yaml";
              output_path = "~/.local/share/warp-oss/themes/noctalia.yaml";
              post_hook = "~/.local/bin/noctalia-apply-warp-theme";
            };
            tuxedo = {
              input_path = "templates/tuxedo.toml";
              output_path = "~/.config/tuxedo/themes/noctalia.toml";
              post_hook = "~/.local/bin/noctalia-apply-tuxedo-theme";
            };
            kopuz = {
              input_path = "templates/kopuz.json";
              output_path = "~/.config/kopuz/noctalia-theme.json";
              post_hook = "~/.local/bin/noctalia-apply-kopuz-theme";
            };
          };
        };
      };
    };
  };
}
