{ pkgs, inputs, ... }:

{
  home-manager.users.user = {
    imports = [
      inputs.noctalia-v4.homeModules.default
    ];

    # Declarative Noctalia plugins. Plugin source is pinned via the
    # noctalia-plugins flake input; settings.json is created at runtime
    # alongside these symlinks (recursive=true builds a real directory).
    xdg.configFile."noctalia/plugins/wallcards" = {
      source = "${inputs.noctalia-plugins}/wallcards";
      recursive = true;
    };

    # Noctalia user templates. These are processed by Noctalia itself whenever
    # the active color scheme changes. Spicetify is handled by Noctalia's built-in
    # template below; Warp OSS needs a custom template.
    xdg.configFile."noctalia/user-templates.toml".text = ''
      [config]

      [templates.vesktop]
      input_path = "~/.config/noctalia/templates/vesktop.css"
      output_path = "~/.config/vesktop/themes/noctalia.css"
      post_hook = "~/.local/bin/noctalia-apply-vesktop-theme"

      [templates.warp_oss]
      input_path = "~/.config/noctalia/templates/warp.yaml"
      output_path = "~/.local/share/warp-oss/themes/noctalia.yaml"
      post_hook = "~/.local/bin/noctalia-apply-warp-theme"

      [templates.obsidian]
      input_path = "~/.config/noctalia/templates/obsidian.css"
      output_path = "~/notes/.obsidian/snippets/noctalia.css"
      post_hook = "~/.local/bin/noctalia-apply-obsidian-theme"

      [templates.tuxedo]
      input_path = "~/.config/noctalia/templates/tuxedo.toml"
      output_path = "~/.config/tuxedo/themes/noctalia.toml"
      post_hook = "~/.local/bin/noctalia-apply-tuxedo-theme"

      [templates.kopuz]
      input_path = "~/.config/noctalia/templates/kopuz.json"
      output_path = "~/.config/kopuz/noctalia-theme.json"
      post_hook = "~/.local/bin/noctalia-apply-kopuz-theme"
    '';

    xdg.configFile."noctalia/templates/vesktop.css".text = ''
      /**
       * @name Noctalia
       * @description Generated by Noctalia on every color-scheme change. Do not edit.
       */

      :root,
      body,
      .visual-refresh,
      .theme-light,
      .theme-dark,
      .theme-darker,
      .theme-midnight {
        color-scheme: dark !important;

        /* Keep Noctalia's generated colors, but expose them as translucent glass. */
        --noctalia-glass: color-mix(in srgb, {{colors.surface.default.hex}} 58%, transparent);
        --noctalia-glass-low: color-mix(in srgb, {{colors.surface_container_low.default.hex}} 46%, transparent);
        --noctalia-glass-high: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 70%, transparent);
        --noctalia-glass-highest: color-mix(in srgb, {{colors.surface_container_highest.default.hex}} 80%, transparent);
        --noctalia-glass-border: color-mix(in srgb, {{colors.outline_variant.default.hex}} 55%, transparent);
        --noctalia-glass-blur: blur(28px) saturate(1.25);
        --noctalia-chat-input: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 32%, transparent);

        --background-primary: var(--noctalia-glass) !important;
        --background-secondary: var(--noctalia-glass-low) !important;
        --background-secondary-alt: var(--noctalia-glass-low) !important;
        --background-tertiary: var(--noctalia-glass-high) !important;
        --background-accent: {{colors.primary.default.hex}} !important;
        --background-floating: var(--noctalia-glass-high) !important;
        --background-modifier-hover: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 62%, transparent) !important;
        --background-modifier-active: var(--noctalia-glass-highest) !important;
        --background-modifier-selected: var(--noctalia-glass-highest) !important;
        --background-modifier-accent: var(--noctalia-glass-border) !important;

        --channeltextarea-background: var(--noctalia-chat-input) !important;
        --modal-background: var(--noctalia-glass) !important;
        --modal-footer-background: var(--noctalia-glass-low) !important;

        --text-normal: {{colors.on_surface.default.hex}} !important;
        --text-muted: {{colors.on_surface_variant.default.hex}} !important;
        --text-link: {{colors.primary.default.hex}} !important;
        --header-primary: {{colors.on_surface.default.hex}} !important;
        --header-secondary: {{colors.on_surface_variant.default.hex}} !important;

        --interactive-normal: {{colors.on_surface.default.hex}} !important;
        --interactive-hover: {{colors.primary.default.hex}} !important;
        --interactive-active: {{colors.primary.default.hex}} !important;
        --interactive-muted: {{colors.outline.default.hex}} !important;

        --brand-experiment: {{colors.primary.default.hex}} !important;
        --brand-experiment-hover: {{colors.primary.default.hex}} !important;
        --mention-foreground: {{colors.primary.default.hex}} !important;
        --mention-background: color-mix(in srgb, {{colors.primary.default.hex}} 18%, transparent) !important;

        --bg-base-primary: var(--noctalia-glass) !important;
        --bg-base-secondary: var(--noctalia-glass-low) !important;
        --bg-base-tertiary: var(--noctalia-glass-low) !important;
        --bg-surface-raised: var(--noctalia-glass-high) !important;
        --bg-mod-faint: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 38%, transparent) !important;
        --bg-mod-subtle: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 55%, transparent) !important;
        --bg-mod-strong: var(--noctalia-glass-highest) !important;
        --background-base-lower: transparent !important;
        --background-surface-high: var(--noctalia-glass-high) !important;
        --background-mod-subtle: color-mix(in srgb, {{colors.surface_container_high.default.hex}} 55%, transparent) !important;
        --background-mod-strong: var(--noctalia-glass-highest) !important;

        --custom-theme-base-color: {{colors.surface.default.hex}} !important;
        --custom-theme-base-color-dark: {{colors.surface.default.hex}} !important;
        --custom-theme-base-color-light: {{colors.surface.default.hex}} !important;
        --custom-theme-primary-color: {{colors.primary.default.hex}} !important;
        --custom-theme-secondary-color: {{colors.secondary.default.hex}} !important;
        --custom-theme-text-color: {{colors.on_surface.default.hex}} !important;
        --custom-theme-text-color-dark: {{colors.on_surface.default.hex}} !important;
        --custom-theme-text-color-light: {{colors.on_surface.default.hex}} !important;
      }

      html,
      body,
      #app-mount,
      #app-mount > div,
      .visual-refresh,
      [class*="appMount_"],
      [class*="app_"],
      [class*="bg_"],
      [class*="layers_"],
      [class*="layer_"],
      [class*="base_"],
      [class*="chat_"],
      [class*="chatContent_"],
      [class*="container_"],
      [class*="content_"],
      [class*="sidebar_"],
      [class*="privateChannels_"],
      [class*="guilds_"],
      [class*="scroller_"],
      [class*="members_"],
      [class*="member_"],
      [class*="panels_"],
      [class*="title_"],
      [class*="themed_"] {
        background-color: transparent !important;
        background: transparent !important;
      }

      /* Single glass layer. The whole Vesktop window is transparent
         (settings.json `transparent: true`), so one backdrop-filter on the
         outermost mount is enough to blur the desktop showing through the
         window. Previously the blur was applied to ~10 nested chrome
         containers (chat/sidebar/members/panels/scrollers/composer/overlays);
         because those nest, each backdrop-filter re-sampled the buffer of the
         one behind it, compounding the blur and producing smearing/ghosting/
         flicker on scroll and on Discord's constant React re-renders. Keeping
         it to one non-nested layer preserves the glass look without the
         compositor artifacts. */
      #app-mount {
        backdrop-filter: var(--noctalia-glass-blur) !important;
      }

      /* Discord's message composer ignores the broad transparent-background
         reset in a few Visual Refresh builds and keeps an opaque
         --channeltextarea-background surface. Pin the composer to the same
         translucent glass used by the rest of Vesktop, without flattening the
         actual editable text area or buttons. */
      [class*="channelTextArea_"] {
        background: transparent !important;
      }

      [class*="channelTextArea_"] [class*="scrollableContainer_"],
      [class*="channelTextArea_"] [class*="themedBackground_"] {
        background: var(--noctalia-chat-input) !important;
        background-color: var(--noctalia-chat-input) !important;
        border: 1px solid var(--noctalia-glass-border) !important;
        box-shadow: none !important;
      }

      [class*="channelTextArea_"] [class*="inner_"],
      [class*="channelTextArea_"] [class*="textArea_"],
      [class*="channelTextArea_"] [class*="slateTextArea_"],
      [class*="channelTextArea_"] [data-slate-editor="true"] {
        background: transparent !important;
        background-color: transparent !important;
      }

      /* Vencord/QuickCSS editor (CodeMirror) */
      .cm-editor,
      .cm-editor .cm-scroller,
      .cm-editor .cm-content {
        background: {{colors.surface.default.hex}} !important;
        color: {{colors.on_surface.default.hex}} !important;
      }

      .cm-editor .cm-gutters {
        background: {{colors.surface_container.default.hex}} !important;
        border-color: {{colors.outline_variant.default.hex}} !important;
        color: {{colors.on_surface_variant.default.hex}} !important;
      }

      .cm-editor .cm-activeLine,
      .cm-editor .cm-activeLineGutter {
        background: {{colors.surface_container_high.default.hex}} !important;
      }

      .cm-editor .cm-cursor {
        border-left-color: {{colors.primary.default.hex}} !important;
      }

      .cm-editor .cm-selectionBackground,
      .cm-editor ::selection {
        background: color-mix(in srgb, {{colors.primary.default.hex}} 35%, transparent) !important;
      }

      /* Mention / ping count badges. The rest of the theme paints everything in
         the scheme's surface/primary tones, which makes unread-ping badges blend
         into the background and become unreadable. Force the Material "error"
         pair so notifications stay high-contrast and obvious. Scope this to the
         count *badges* only — NOT unreadMentionsIndicatorTop_/Bottom_, the
         floating jump-bars pinned to the top/bottom of a scroller. Those bar
         containers render even when empty, so coloring them paints solid error
         blocks at the list edges with nothing to clear. */
      [class*="numberBadge_"],
      [class*="mentionsBadge_"] {
        background-color: {{colors.error.default.hex}} !important;
        color: {{colors.on_error.default.hex}} !important;
        backdrop-filter: none !important;
      }

      /* Apple San Francisco system font (installed via the apple-fonts flake
         input). SF Pro for the UI, Nerd-patched SF Mono for code/monospace. */
      :root {
        --font-primary: "SF Pro Display", sans-serif !important;
        --font-display: "SF Pro Display", sans-serif !important;
        --font-headline: "SF Pro Display", sans-serif !important;
        --font-code: "SFMono Nerd Font", monospace !important;
      }
    '';

    # Obsidian theme snippet. Obsidian has no native Noctalia template, so we
    # render a CSS snippet that maps the active color scheme onto Obsidian's
    # built-in CSS variables. Obsidian watches its snippets folder and
    # hot-reloads the snippet whenever its content changes — no restart needed.
    # The snippet still has to be *enabled* once, which the post_hook does.
    xdg.configFile."noctalia/templates/obsidian.css".text = ''
      /* Generated by Noctalia on every color-scheme change. Do not edit. */
      .theme-dark {
        --background-primary:           {{colors.surface.default.hex}};
        --background-primary-alt:       {{colors.surface_container_low.default.hex}};
        --background-secondary:         {{colors.surface_container.default.hex}};
        --background-secondary-alt:     {{colors.surface_container_high.default.hex}};

        --background-modifier-border:        {{colors.outline_variant.default.hex}};
        --background-modifier-border-hover:  {{colors.outline.default.hex}};
        --background-modifier-border-focus:  {{colors.primary.default.hex}};
        --background-modifier-hover:         {{colors.surface_container_high.default.hex}};
        --background-modifier-active-hover:  {{colors.surface_container_highest.default.hex}};

        --text-normal:  {{colors.on_surface.default.hex}};
        --text-muted:   {{colors.on_surface_variant.default.hex}};
        --text-faint:   {{colors.outline.default.hex}};

        --text-accent:        {{colors.primary.default.hex}};
        --text-accent-hover:  {{colors.tertiary.default.hex}};
        --text-on-accent:     {{colors.on_primary.default.hex}};

        --interactive-normal:        {{colors.surface_container.default.hex}};
        --interactive-hover:         {{colors.surface_container_high.default.hex}};
        --interactive-accent:        {{colors.primary.default.hex}};
        --interactive-accent-hover:  {{colors.tertiary.default.hex}};

        --text-selection:     {{colors.secondary_container.default.hex}};
        --text-highlight-bg:  {{colors.tertiary_container.default.hex}};

        --titlebar-background:          {{colors.surface_container.default.hex}};
        --titlebar-background-focused:  {{colors.surface_container_high.default.hex}};

        --scrollbar-thumb-bg:         {{colors.outline_variant.default.hex}};
        --scrollbar-active-thumb-bg:  {{colors.outline.default.hex}};
      }
    '';

    # One-time enable of the rendered snippet. appearance.json is owned by
    # Obsidian's runtime (and Syncthing-synced), so we merge in place with jq
    # rather than symlinking it. Idempotent: only writes when "noctalia" is not
    # already in enabledCssSnippets.
    home.file.".local/bin/noctalia-apply-obsidian-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        appearance="$HOME/notes/.obsidian/appearance.json"
        [[ -d "$HOME/notes/.obsidian" ]] || exit 0
        [[ -f "$appearance" ]] || echo '{}' > "$appearance"

        if jq -e '(.enabledCssSnippets // []) | index("noctalia")' "$appearance" >/dev/null; then
          exit 0
        fi

        tmp="$appearance.tmp"
        jq '.enabledCssSnippets = ((.enabledCssSnippets // []) + ["noctalia"] | unique)' \
          "$appearance" > "$tmp"
        mv "$tmp" "$appearance"
      '';
    };

    home.file.".local/bin/noctalia-apply-vesktop-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        settings="$HOME/.config/vesktop/settings/settings.json"
        mkdir -p "$HOME/.config/vesktop/settings" "$HOME/.config/vesktop/themes"

        if [ ! -s "$settings" ]; then
          printf '%s\n' '{"enabledThemes":["noctalia.css"],"transparent":true}' > "$settings"
          exit 0
        fi

        tmp=$(mktemp)
        jq '
          .transparent = true
          | .enabledThemes = (
              ((.enabledThemes // [])
                | map(select(. != "noctalia.theme.css" and . != "noctalia-material.theme.css")))
              + ["noctalia.css"]
              | unique
            )
        ' "$settings" > "$tmp"
        mv "$tmp" "$settings"
      '';
    };

    xdg.configFile."noctalia/templates/warp.yaml".text = ''
      name: Noctalia
      accent: '{{colors.primary.default.hex}}'
      background: '{{colors.surface.default.hex}}'
      foreground: '{{colors.on_surface.default.hex}}'
      details: darker
      terminal_colors:
        normal:
          black: '{{colors.surface_variant.default.hex}}'
          red: '{{colors.error.default.hex}}'
          green: '{{colors.primary.default.hex}}'
          yellow: '{{colors.secondary.default.hex}}'
          blue: '{{colors.tertiary.default.hex}}'
          magenta: '{{colors.primary_fixed_dim.default.hex}}'
          cyan: '{{colors.secondary_fixed_dim.default.hex}}'
          white: '{{colors.on_surface.default.hex}}'
        bright:
          black: '{{colors.on_surface_variant.default.hex}}'
          red: '{{colors.error.default.hex}}'
          green: '{{colors.primary.default.hex}}'
          yellow: '{{colors.secondary.default.hex}}'
          blue: '{{colors.tertiary.default.hex}}'
          magenta: '{{colors.primary_fixed_dim.default.hex}}'
          cyan: '{{colors.secondary_fixed_dim.default.hex}}'
          white: '{{colors.on_surface.default.hex}}'
    '';

    xdg.configFile."noctalia/templates/tuxedo.toml".text = ''
      name = Noctalia
      bg = {{colors.surface.default.hex}}
      panel = {{colors.surface_container.default.hex}}
      border = {{colors.outline_variant.default.hex}}
      fg = {{colors.on_surface.default.hex}}
      dim = {{colors.on_surface_variant.default.hex}}
      accent = {{colors.primary.default.hex}}
      cursor = {{colors.surface_container_high.default.hex}}
      selection = {{colors.surface_container_highest.default.hex}}
      statusbar = {{colors.surface_container.default.hex}}
      status_fg = {{colors.on_surface.default.hex}}
      mode_fg = {{colors.on_primary.default.hex}}
      mode_bg = {{colors.primary.default.hex}}
      pri_a = {{colors.error.default.hex}}
      pri_b = {{colors.secondary.default.hex}}
      pri_c = {{colors.primary.default.hex}}
      pri_d = {{colors.tertiary.default.hex}}
      pri_other = {{colors.primary_fixed_dim.default.hex}}
      project = {{colors.primary.default.hex}}
      context = {{colors.secondary.default.hex}}
      due = {{colors.secondary.default.hex}}
      overdue = {{colors.error.default.hex}}
      today = {{colors.error.default.hex}}
      done = {{colors.outline.default.hex}}
      selected = {{colors.surface_container_high.default.hex}}
      matched = {{colors.tertiary.default.hex}}
    '';

    # Kopuz music player. A kopuz theme is a map of 13 semantic color keys
    # (config.custom_themes."<id>".vars) that the app rewrites into its own
    # --color-* CSS variables at runtime. We render just those vars here as a
    # standalone JSON object; the post_hook merges it into kopuz's config.json
    # under a "custom-noctalia" theme and selects it, leaving the rest of the
    # config (library, server creds, last.fm keys) untouched.
    xdg.configFile."noctalia/templates/kopuz.json".text = ''
      {
        "bg": "{{colors.surface.default.hex}}",
        "raised": "{{colors.surface_container.default.hex}}",
        "surface": "{{colors.outline.default.hex}}",
        "text": "{{colors.on_surface.default.hex}}",
        "text-muted": "{{colors.on_surface_variant.default.hex}}",
        "progress": "{{colors.primary.default.hex}}",
        "accent-soft": "{{colors.tertiary.default.hex}}",
        "accent": "{{colors.primary.default.hex}}",
        "accent-alt": "{{colors.secondary.default.hex}}",
        "accent-deep": "{{colors.primary_fixed_dim.default.hex}}",
        "highlight": "{{colors.secondary.default.hex}}",
        "highlight-dark": "{{colors.tertiary.default.hex}}",
        "danger": "{{colors.error.default.hex}}"
      }
    '';

    home.file.".local/bin/noctalia-apply-warp-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        set_theme() {
          local cfgdir=$1 settings backup
          settings="$cfgdir/settings.toml"
          [[ -f "$settings" ]] || return 0
          backup="$settings.bak-before-noctalia-sync"
          [[ -f "$backup" ]] || cp -p "$settings" "$backup"
          awk '
            BEGIN { in_themes=0; wrote=0 }
            /^\[appearance\.themes\]/ { print; in_themes=1; next }
            /^\[/ && in_themes { if (!wrote) { print "system_theme = false"; print "theme = { custom = { name = \"Noctalia\", path = \"noctalia.yaml\" } }"; wrote=1 } in_themes=0 }
            in_themes && /^system_theme[[:space:]]*=/ { next }
            in_themes && /^theme[[:space:]]*=/ { next }
            { print }
            END { if (in_themes && !wrote) { print "system_theme = false"; print "theme = { custom = { name = \"Noctalia\", path = \"noctalia.yaml\" } }" } }
          ' "$settings" > "$settings.tmp"
          mv "$settings.tmp" "$settings"
        }

        set_theme "$HOME/.config/warp-oss"
      '';
    };

    home.file.".local/bin/noctalia-apply-tuxedo-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        cfg="$HOME/.config/tuxedo/config.toml"
        mkdir -p "$(dirname "$cfg")" "$HOME/.config/tuxedo/themes"
        touch "$cfg"
        if grep -q '^theme[[:space:]]*=' "$cfg"; then
          sed -i 's/^theme[[:space:]]*=.*/theme = Noctalia/' "$cfg"
        else
          tmp=$(mktemp)
          printf 'theme = Noctalia\n' > "$tmp"
          cat "$cfg" >> "$tmp"
          mv "$tmp" "$cfg"
        fi
      '';
    };

    home.file.".local/bin/noctalia-apply-kopuz-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        cfg="$HOME/.config/kopuz/config.json"
        vars="$HOME/.config/kopuz/noctalia-theme.json"
        # config.json is created on first run; the rendered vars come from the
        # Noctalia template. Do nothing until both exist.
        [ -s "$cfg" ] || exit 0
        [ -s "$vars" ] || exit 0

        tmp=$(mktemp)
        jq --slurpfile v "$vars" \
          '.custom_themes."custom-noctalia" = { name: "Noctalia", vars: $v[0] }
           | .theme = "custom-noctalia"' \
          "$cfg" > "$tmp"
        mv "$tmp" "$cfg"
      '';
    };

    programs.noctalia-shell = {
      enable = true;

      # wallcards plugin pulls Qt5Compat.GraphicalEffects, which isn't in
      # the default noctalia QML import path — inject qt6.qt5compat so the
      # plugin's window can render.
      package = inputs.noctalia-v4.packages.${pkgs.stdenv.hostPlatform.system}.default.overrideAttrs (old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ pkgs.qt6.qt5compat ];
      });

      settings = {
        bar = {
          barType = "framed";
          position = "top";
          monitors = [];
          density = "compact";
          showOutline = false;
          showCapsule = true;
          capsuleOpacity = 0.37;
          capsuleColorKey = "none";
          widgetSpacing = 6;
          contentPadding = 2;
          fontScale = 1;
          backgroundOpacity = 0.37;
          useSeparateOpacity = true;
          floating = false;
          marginVertical = 4;
          marginHorizontal = 4;
          frameThickness = 8;
          frameRadius = 12;
          outerCorners = true;
          hideOnOverview = false;
          displayMode = "always_visible";
          autoHideDelay = 500;
          autoShowDelay = 150;
          showOnWorkspaceSwitch = true;
          screenOverrides = [];
          widgets = {
            left = [
              {
                id = "ControlCenter";
                useDistroLogo = true;
                icon = "noctalia";
                colorizeDistroLogo = false;
                colorizeSystemIcon = "none";
                customIconPath = "";
                enableColorization = false;
              }
            ];
            center = [
              {
                id = "Workspace";
                labelMode = "name";
                hideUnoccupied = true;
                characterCount = 2;
                colorizeIcons = false;
                emptyColor = "secondary";
                enableScrollWheel = true;
                focusedColor = "primary";
                followFocusedScreen = false;
                groupedBorderOpacity = 1;
                iconScale = 0.8;
                occupiedColor = "secondary";
                pillSize = 0.6;
                showApplications = false;
                showBadge = true;
                showLabelsOnlyWhenOccupied = true;
                unfocusedIconsOpacity = 1;
              }
            ];
            right = [
              {
                id = "Clock";
                formatHorizontal = "dd MMM hh:mm AP";
                formatVertical = "hh mm AP - dd MM";
                tooltipFormat = "hh:mm AP ddd MMM dd";
                clockColor = "none";
                customFont = "";
                useCustomFont = false;
              }
            ];
          };
        };

        general = {
          avatarImage = "/home/user/.face";
          dimmerOpacity = 0.2;
          showScreenCorners = false;
          forceBlackScreenCorners = false;
          scaleRatio = 1;
          radiusRatio = 0.8;
          iRadiusRatio = 1;
          boxRadiusRatio = 1;
          screenRadiusRatio = 1;
          animationSpeed = 1;
          animationDisabled = false;
          compactLockScreen = false;
          lockScreenAnimations = false;
          lockOnSuspend = true;
          showSessionButtonsOnLockScreen = true;
          showHibernateOnLockScreen = false;
          enableShadows = true;
          shadowDirection = "bottom_right";
          shadowOffsetX = 2;
          shadowOffsetY = 3;
          language = "";
          allowPanelsOnScreenWithoutBar = true;
          showChangelogOnStartup = true;
          telemetryEnabled = false;
          enableLockScreenCountdown = true;
          lockScreenCountdownDuration = 10000;
          autoStartAuth = false;
          allowPasswordWithFprintd = false;
          clockStyle = "custom";
          clockFormat = "hh\\nmm AP";
          passwordChars = false;
          lockScreenMonitors = [];
          lockScreenBlur = 0;
          lockScreenTint = 0;
          reverseScroll = false;
        };

        ui = {
          fontDefault = "SF Pro Display";
          fontFixed = "SFMono Nerd Font";
          fontDefaultScale = 1;
          fontFixedScale = 1;
          tooltipsEnabled = true;
          boxBorderEnabled = false;
          panelBackgroundOpacity = 0.37;
          panelsAttachedToBar = true;
          settingsPanelMode = "attached";
          settingsPanelSideBarCardStyle = false;
        };

        location = {
          name = "Example City";
          weatherEnabled = true;
          weatherShowEffects = true;
          useFahrenheit = true;
          use12hourFormat = true;
          showWeekNumberInCalendar = false;
          showCalendarEvents = true;
          showCalendarWeather = true;
          analogClockInCalendar = false;
          firstDayOfWeek = -1;
          hideWeatherTimezone = false;
          hideWeatherCityName = false;
        };

        calendar = {
          cards = [
            { enabled = true; id = "calendar-header-card"; }
            { enabled = true; id = "calendar-month-card"; }
            { enabled = true; id = "weather-card"; }
          ];
        };

        wallpaper = {
          enabled = true;
          overviewEnabled = false;
          directory = "/home/user/Pictures/Wallpapers";
          monitorDirectories = [];
          enableMultiMonitorDirectories = false;
          showHiddenFiles = false;
          viewMode = "single";
          setWallpaperOnAllMonitors = true;
          fillMode = "crop";
          fillColor = "#000000";
          useSolidColor = false;
          solidColor = "#1a1a2e";
          automationEnabled = false;
          wallpaperChangeMode = "random";
          randomIntervalSec = 300;
          transitionDuration = 1500;
          transitionType = "random";
          skipStartupTransition = false;
          transitionEdgeSmoothness = 0.05;
          panelPosition = "follow_bar";
          hideWallpaperFilenames = false;
          overviewBlur = 0.4;
          overviewTint = 0.6;
          useWallhaven = false;
          wallhavenQuery = "";
          wallhavenSorting = "relevance";
          wallhavenOrder = "desc";
          wallhavenCategories = "111";
          wallhavenPurity = "100";
          wallhavenRatios = "";
          wallhavenApiKey = "";
          wallhavenResolutionMode = "atleast";
          wallhavenResolutionWidth = "";
          wallhavenResolutionHeight = "";
          sortOrder = "name";
          favorites = [];
        };

        appLauncher = {
          enableClipboardHistory = true;
          autoPasteClipboard = false;
          enableClipPreview = true;
          clipboardWrapText = true;
          clipboardWatchTextCommand = "wl-paste --type text --watch cliphist store";
          clipboardWatchImageCommand = "wl-paste --type image --watch cliphist store";
          position = "center";
          pinnedApps = [];
          useApp2Unit = true;
          sortByMostUsed = true;
          terminalCommand = "warp-oss";
          customLaunchPrefixEnabled = false;
          customLaunchPrefix = "";
          viewMode = "list";
          showCategories = false;
          iconMode = "tabler";
          showIconBackground = false;
          enableSettingsSearch = true;
          enableWindowsSearch = true;
          enableSessionSearch = true;
          ignoreMouseInput = true;
          screenshotAnnotationTool = "";
          overviewLayer = false;
          density = "compact";
        };

        controlCenter = {
          position = "close_to_bar_button";
          diskPath = "/";
          shortcuts = {
            left = [
              { id = "Network"; }
              { id = "Bluetooth"; }
              { id = "WallpaperSelector"; }
              { id = "NoctaliaPerformance"; }
            ];
            right = [
              { id = "Notifications"; }
              { id = "KeepAwake"; }
              { id = "NightLight"; }
            ];
          };
          cards = [
            { enabled = true; id = "profile-card"; }
            { enabled = true; id = "shortcuts-card"; }
            { enabled = true; id = "audio-card"; }
            { enabled = true; id = "weather-card"; }
            { enabled = true; id = "media-sysmon-card"; }
          ];
        };

        systemMonitor = {
          cpuWarningThreshold = 80;
          cpuCriticalThreshold = 90;
          tempWarningThreshold = 80;
          tempCriticalThreshold = 90;
          gpuWarningThreshold = 80;
          gpuCriticalThreshold = 90;
          memWarningThreshold = 80;
          memCriticalThreshold = 90;
          swapWarningThreshold = 80;
          swapCriticalThreshold = 90;
          diskWarningThreshold = 80;
          diskCriticalThreshold = 90;
          diskAvailWarningThreshold = 20;
          diskAvailCriticalThreshold = 10;
          batteryWarningThreshold = 20;
          batteryCriticalThreshold = 5;
          enableDgpuMonitoring = true;
          useCustomColors = false;
          warningColor = "";
          criticalColor = "";
          externalMonitor = "resources || missioncenter || jdsystemmonitor || corestats || system-monitoring-center || gnome-system-monitor || plasma-systemmonitor || mate-system-monitor || ukui-system-monitor || deepin-system-monitor || pantheon-system-monitor";
        };

        dock = {
          enabled = false;
          position = "bottom";
          displayMode = "auto_hide";
          dockType = "floating";
          backgroundOpacity = 1;
          floatingRatio = 1;
          size = 1;
          onlySameOutput = true;
          monitors = [];
          pinnedApps = [];
          colorizeIcons = false;
          showLauncherIcon = false;
          launcherPosition = "end";
          launcherIconColor = "none";
          pinnedStatic = false;
          inactiveIndicators = false;
          groupApps = false;
          groupContextMenuMode = "extended";
          groupClickAction = "cycle";
          groupIndicatorStyle = "dots";
          deadOpacity = 0.6;
          animationSpeed = 1;
          sitOnFrame = false;
          showFrameIndicator = true;
        };

        network = {
          wifiEnabled = true;
          airplaneModeEnabled = false;
          bluetoothRssiPollingEnabled = false;
          bluetoothRssiPollIntervalMs = 60000;
          networkPanelView = "wifi";
          wifiDetailsViewMode = "grid";
          bluetoothDetailsViewMode = "grid";
          bluetoothHideUnnamedDevices = false;
          disableDiscoverability = false;
        };

        sessionMenu = {
          enableCountdown = true;
          countdownDuration = 10000;
          position = "center";
          showHeader = true;
          showKeybinds = true;
          largeButtonsStyle = true;
          largeButtonsLayout = "single-row";
          powerOptions = [
            { action = "lock"; enabled = true; keybind = "1"; }
            { action = "suspend"; enabled = true; keybind = "2"; }
            { action = "hibernate"; enabled = true; keybind = "3"; }
            { action = "reboot"; enabled = true; keybind = "4"; }
            { action = "logout"; enabled = true; keybind = "5"; }
            { action = "shutdown"; enabled = true; keybind = "6"; }
            { action = "rebootToUefi"; enabled = true; keybind = "7"; }
          ];
        };

        notifications = {
          enabled = true;
          enableMarkdown = false;
          density = "default";
          monitors = [];
          location = "top_right";
          overlayLayer = true;
          backgroundOpacity = 0.37;
          respectExpireTimeout = false;
          lowUrgencyDuration = 3;
          normalUrgencyDuration = 8;
          criticalUrgencyDuration = 15;
          clearDismissed = true;
          saveToHistory = {
            low = true;
            normal = true;
            critical = true;
          };
          sounds = {
            enabled = false;
            volume = 0.5;
            separateSounds = false;
            criticalSoundFile = "";
            normalSoundFile = "";
            lowSoundFile = "";
            excludedApps = "vesktop,firefox,chrome,chromium,edge";
          };
          enableMediaToast = false;
          enableKeyboardLayoutToast = true;
          enableBatteryToast = true;
        };

        osd = {
          enabled = true;
          location = "top_right";
          autoHideMs = 2000;
          overlayLayer = true;
          backgroundOpacity = 1;
          enabledTypes = [ 0 1 2 ];
          monitors = [];
        };

        audio = {
          volumeStep = 5;
          volumeOverdrive = false;
          cavaFrameRate = 30;
          visualizerType = "linear";
          mprisBlacklist = [];
          preferredPlayer = "";
          volumeFeedback = false;
          volumeFeedbackSoundFile = "";
        };

        brightness = {
          brightnessStep = 5;
          enforceMinimum = true;
          enableDdcSupport = false;     # Set to true if you want Noctalia to control monitor brightness via DDC
          backlightDeviceMappings = [];
        };

        colorSchemes = {
          useWallpaperColors = true;
          darkMode = true;
          schedulingMode = "off";
          manualSunrise = "06:30";
          manualSunset = "18:30";
          generationMethod = "tonal-spot";
          monitorForColors = "";
        };

        templates = {
          # Firefox template is for the backup browser only. Helium is the primary
          # browser and is launched by the niri Mod+B bind above.
          activeTemplates = [
            { id = "firefox"; enabled = true; }
            { id = "discord"; enabled = true; }
            { id = "helix"; enabled = true; }
            # Built-in starship template: injects a marker-delimited
            # [palettes.noctalia] block into ~/.config/starship.toml on every
            # color-scheme change (same mechanism laptop's v5 builtin uses).
            { id = "starship"; enabled = true; }
          ];
          enableUserTheming = true;
        };

        nightLight = {
          enabled = false;
          forced = false;
          autoSchedule = true;
          nightTemp = "4000";
          dayTemp = "6500";
          manualSunrise = "06:30";
          manualSunset = "18:30";
        };

        hooks = {
          enabled = true;
          wallpaperChange = "";
          darkModeChange = "";
          screenLock = "playerctl pause";
          screenUnlock = "";
          performanceModeEnabled = "";
          performanceModeDisabled = "";
          startup = "";
          session = "";
        };

        plugins = {
          autoUpdate = false;
        };

        idle = {
          enabled = true;
          screenOffTimeout = 600;
          lockTimeout = 660;
          suspendTimeout = 0;
          fadeDuration = 5;
          customCommands = "[]";
        };

        desktopWidgets = {
          enabled = false;
          overviewEnabled = true;
          gridSnap = false;
          monitorWidgets = [];
        };
      };
    };
  };
}
